<?php
    $this->load->view("plantillas/back_end/header");
    $this->load->view("plantillas/back_end/menu");
    $this->load->view("front_end/".$contenido);
    if($vista=="paciente"){
        $this->load->view("plantillas/back_end/footer_paciente");
    }
    elseif($vista=="usuarios"){
        $this->load->view("plantillas/back_end/footer_usuario");
    }
    elseif($vista=="medicos"){
        $this->load->view("plantillas/back_end/footer_medico");
    }
    else{
	
    if($tipocalendar=='agendaDay'){
        $this->load->view("plantillas/back_end/footer_diario");
    }
    elseif($tipocalendar=='agendaWeek'){
        $this->load->view("plantillas/back_end/footer");
    }
?>